services:
  - type: web
    name: predictcetaceans
    env: python
    plan: free
    pythonVersion: 3.10.10
    buildCommand:  pip install -r requirements.txt
    startCommand: gunicorn app_v2:app --bind 0.0.0.0:$PORT

